### ISSUE TITLE
CaptureConsole Integration

### ISSUE THREAD

**Issue by 3zzy** [nuxt-community/sentry-module#191]
Not sure if its because its new but the most important pluggable integration is missing: https://docs.sentry.io/platforms/node/pluggable-integrations/#captureconsole

It would be great to have it.

**Comment by rchl** [comment]
> the most important pluggable integration

This statement seems a bit of an exaggeration to me :)
Can you explain why do you think so?

When errors are reported then previous console calls are included in those reports.

Reporting console calls themselves as separate "issues" is not something that most would want by default, I would say. That's why it's not enabled by default but you can easily enable it yourself through configuration.
