### ISSUE TITLE
Allow plugins from outside @sentry/integrations

### ISSUE THREAD

**Issue by axwalker** [nuxt-community/sentry-module#240]
### Is your feature request related to a problem? Please describe.
I'd like to use the [Sentry rrweb plugin](https://docs.sentry.io/platforms/javascript/configuration/integrations/rrweb/) to have session replays with some of my errors. However, it seems I can only add integrations that are part of `@sentry/integrations` because of the way they are imported and used [here](https://github.com/nuxt-community/sentry-module/blob/master/lib/plugin.client.js#L4).

### Describe the solution you'd like
The ability to declare plugins from outside of `@sentry/integrations` (eg. `import SentryRRWeb from "@sentry/rrweb"`). I'm not sure what the best way would be to alter the current configuration in `nuxt.config.js` to facilitate this. 

### Describe alternatives you've considered
I don't know any other ways to solve this at the moment.

**Comment by williamlimianto** [comment]
Hi @axwalker,
Actually, I'm eager to wait for this implementation as well.

However, after I checked the `.$sentry` via `console.log()`, I think I found an momentarily solution for this case.
I saw that there's a `init()` method that actually is the same as how we set up the Sentry + rrweb in VueJS.

![image](https://user-images.githubusercontent.com/7065829/96839358-436ddc80-1473-11eb-9aed-2f1235c24c47.png)

That strikes me with an idea and here's what I did. I created a plugin file inside of the plugins folder like this :

```
import { Integrations } from "@sentry/tracing";
import SentryRRWeb from '@sentry/rrweb';

export default (context) => {
    if(process.client){
        console.log(context.$sentry);
        context.$sentry.init({
            dsn: 'YOUR_DSN_KEY',
            integrations: [
                new Integrations.BrowserTracing(),
                new SentryRRWeb({
                // ...options
                checkoutEveryNms: 5 * 60 * 1000,
                }),
            ],

            // We recommend adjusting this value in production, or using tracesSampler
            // for finer control
            tracesSampleRate: 1.0,
        });
    }
};
```
_**Note: process.client is required due to the SentryRRWeb is using the window global variable from the client's browser.
(Server doesn't have `window` obviously).**_

Next, register the `plugin` at the nuxt.config.js file like this :
```
plugins: [
   '~/plugins/sentry-nuxt-rrweb.js'
],
```

And that's it, you can now use the rrweb with `@nextjs/sentry`.
I know this step is quite 'hacky', but I think it is worth to try.

**Comment by rchl** [comment]
Implementing in #276
