### ISSUE TITLE
Sentry Tracing on SSR

### ISSUE THREAD

**Issue by prillymonials** [nuxt-community/sentry-module#264]
### Version
@nuxtjs/sentry: 4.5.0
@sentry/tracing: 5.29.2
nuxt: 2.10.2

### Sentry configuration
```
{
    dsn: <dsn>,
    disabled: false,
    config: {
      environment: 'production'
    },
    tracing: true,
    clientConfig: {
      beforeSend(event) {
        return event;
      },
      release: `app@${process.env.npm_package_version}`
  }
}
```

### Reproduction Link

N/A

### Steps to reproduce

1. Open web apps
2. Inspect Element

### What is Expected?

Run without error

### What is actually happening?

Has error and stop the applications
![image](https://user-images.githubusercontent.com/11346216/104286319-76aa8f80-54e7-11eb-8917-8a79127054ff.png)

**Comment by rchl** [comment]
This looks like a client error so not sure why you mention SSR.

I can't really figure out the issue based on this error alone. Ideally, create a minimal project that reproduces. You could even use your real DSN since it's not really sensitive information.

Also, make sure you are using some decently recent node version. I'm not sure what's the current requirement for Sentry but I would with 12 at least.

**Comment by prillymonials** [comment]
Hi @rchl thank you for the replies, I tried in the minimal repository, and it working perfectly.
https://codesandbox.io/s/nuxt-sentry-s8tuq
So any ideas of `scope.getTransaction` error?

**Comment by rchl** [comment]
No, no ideas. Starts with your failing project and remove various bits and pieces (including dependencies), until you find the issue.

**Comment by prillymonials** [comment]
Okay thank you, let me close the issue

**Comment by prillymonials** [comment]
Hi @rchl 
Update for this issue:
Need to remove `@sentry/browser`.
Thank you

**Comment by rchl** [comment]
OK. So then I suppose the issue was due to various `@sentry` packages using incompatible versions since other `@sentry` packages that come from this module had different versions.
