### ISSUE TITLE
Help wanted: tests

### ISSUE THREAD

**Issue by DiederikvandenB** [nuxt-community/sentry-module#27]
To everyone using this package:

If anyone could help out to write a few basic tests that would be great. I'd be willing to maintain the package although I do not use Vue/Nuxt myself anymore, and having tests would make this much easier. I unfortunately do not have enough spare time available to write the tests myself.

Cheers!

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c19">#c19</a>)</em></sub></div>

**Comment by sobolevn** [comment]
@DiederikvandenB I am willing to do that.

I guess we can use `raven-testkit` to emulate actual event publishing.

Testing strategy should include:
1. testing client side errors
2. testing server side errors
Since they really differ in real life apps.

I think the best to do it is to use `cypress` with raw `jest` tests. 

Do you have any extra ideas that should be addressed?

**Comment by DiederikvandenB** [comment]
Sorry for the tardy response, I'm away on holiday.

Great news that you are willing to take this on. Agreed with your suggestions 👍

**Comment by rchl** [comment]
Sentry-testkit https://wix.github.io/sentry-testkit/#/getting-started/
