### ISSUE TITLE
uBlock Origin blocks requests

### ISSUE THREAD

**Issue by gokhan-cinar** [nuxt-community/sentry-module#271]
Hello everyone,

I get this error when using uBlock:

console error;

`POST https://sentry.io/api/1723003/store/?sentry_key=KEY&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT`

### Version
@nuxtjs/sentry: 3.0.1
nuxt: 2.11.0

can you help me ?

**Comment by rchl** [comment]
What would you expect this module to do about it? It's an issue local to your system (and those who use as blocker).

**Comment by gokhan-cinar** [comment]
@rchl  uBlock is active and many parts of the project are not working. If you want to test link: https://scoutium.com/

**Comment by rchl** [comment]
I feel that it's the user's right to block anything he feels like. If you really don't want to prevent that then you can host Sentry yourself and send the reports to your own domain.

That said, I'm not sure I agree with uBlock blocking sentry domain by default (assuming it does that by default) since it's not really related to advertising.

**Comment by salv0** [comment]
I know that this is closed already, but for anyone else coming here through a Google search, there is a solution for the issue, which requires using the 'tunnel' option.
You can find more information here: https://docs.sentry.io/platforms/javascript/troubleshooting/#using-the-tunnel-option

On AWS, a possibility is creating a simple lambda to handle it if you don't have a backend
