### ISSUE TITLE
Sentry make project crash still on 5.0.3

### ISSUE THREAD

**Issue by lustan3216** [nuxt-community/sentry-module#289]
### Version
@nuxtjs/sentry: 5.0.3
nuxt: 2.15.2

### Sentry configuration
No configuration but `dsn`

### Steps to reproduce
1. Set `dsn` only
2. nuxt build
3. nuxt start

### What is Expected?
The project can work like normal.

### What is actually happening?
The project can not execute any action anymore, it stops and the tab can not close either.
I can hear the fan of my computer works very loudly.

**Comment by rchl** [comment]
Does it work if you revert to an older version? If so, please try to find the exact version where it stopped working for you.

**Comment by lustan3216** [comment]
I will try that, thanks.

**Comment by rchl** [comment]
Feel free to reopen when you have more information.
Can do anything based on the information I have right now.

**Comment by migo315** [comment]
I had the same symptoms. In my project I have several lists with filters. When I enable or disable a filter, I use $router.replace to change the query params. Activating worked, deactivating didn't work anymore. The browser is frozen. The NuxtJs application stopped working. In the console log it says "Duplicate Navigation". 

With Sentry disabled the browser is not frozen and the application works (still showing the error). I am using version 4, but updating to 5 did not solve the problem either.

Meanwhile it works again, because I use $router.push instead of $router.replace. But of course this doesn't solve the real problem, which is that Sentry freezes the browser in a certain combination.

A few days ago this had worked with $router.replace. But I made a lot of changes, so I don't know exactly which change is responsible.

For Sentry, I have only configured the DSN. NuxtJs in version 2.15.8.

I will try to provide an example project.

**Comment by migo315** [comment]
@shivam-deepsource Not really. I still use $router.push instead of $router.replace as workaround.

**Comment by rchl** [comment]
I believe that the freeze you are seeing is due to this Sentry SDK issue: https://github.com/getsentry/sentry-javascript/issues/4186

I have made a workaround for that in https://github.com/nuxt-community/sentry-module/releases/tag/v5.1.7 . Feel free to try it out.

(I'm also [fixing it in the Sentry SDK](https://github.com/getsentry/sentry-javascript/pull/4487) itself but with the workaround in the Nuxt module it should work already)
