### ISSUE TITLE
Tracking failed axios requests automatically

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/sentry-module#304]
I have an issue with my Sentry issue panel being flooded with failing 404 requests, and I'd like to disable this, but not sure how.

I have made a global handler to track failed axios requests, but I have specifically disabled 404 errors from being caught:

	$axios.onError((error) => {
		if (error.response?.status !== 404) {
			$sentry.captureException(error)
		}

		nuxtError({
		statusCode: error.response?.status || 500,
		message: error.message + ': ' + JSON.stringify(error.response?.data)
		});
		
		return Promise.reject(error);
	})

However, I still do see a lot of these issues in Sentry:

![image](https://user-images.githubusercontent.com/3786627/113556311-92ac6180-95fc-11eb-9901-6b43cfc920f8.png)

So there must be some global exception handler that I haven't seen documented.

Any ideas?

**Comment by rchl** [comment]
There is a global exception handler registered since otherwise this module would not catch any errors by itself and the user would need to call the `captureException` or other Sentry API manually. And that would be rather beside the point as the point is that Sentry catches all unhandled exceptions.

Your code returns a promise rejection from the interceptor which means that, if the exception is not handled at the axios call site, it will propagate to the global handler and be reported. Even if it's not a 404 error, your code likely results in reporting it twice, once manually by you and once by the global handler. By luck, you might not be seeing duplicates as Sentry might be filtering out the second one due to being similar.

**Comment by simplenotezy** [comment]
@rchl Thanks for your in-depth answer. Take makes perfect sense. However, how do I tell the Sentry module to ignore 404 errors? I already catch any errors where I use $axios.

**Comment by rchl** [comment]
That interceptor logic seems a bit weird. If you are calling `nuxtError` then likely you want to return a resolved promise rather than rejected one (see also the example in the Nuxt axios module: https://axios.nuxtjs.org/helpers ).

But then you also have to make sure that the place that uses axios handles returned value appropriately. I believe the Nuxt error function will show an error in asynchronous way so the following code will still execute.

**Comment by simplenotezy** [comment]
@rchl Thanks for your prompt reply. So you suggest I don't call nuxtError()? Or should I still call nuxtError(), but just return an `Promise.reject(false)`?

**Comment by rchl** [comment]
Maybe log the `error.config` so that you know better which axios request is trigger the report. Then check around and try to find out why it might be propagating to the global handler. It does look like it's a request error that is not being caught but I can't tell more without access to the code.

**Comment by rchl** [comment]
I'm assuming it's solved or you have all information to figure it out. Feel free to post back if there is something more.
