### ISSUE TITLE
Upgrade sentry.javascript.browser to v6.3.1

### ISSUE THREAD

**Issue by hydRAnger** [nuxt-community/sentry-module#311]
### Is your feature request related to a problem? Please describe.
As current sentry.javascript.browse is v6.2.5, in Sentry dashboard will receive:
```
Seems like your SDKs could use a refresh. We recommend updating these SDKs to make sure you’re getting all the data you need.
@v6.2.5 update to version 6.3.1
```

### Describe the solution you'd like
update sentry.javascript.browser to v6.3.1

**Comment by rchl** [comment]
The dependencies are getting update fairly regularly through the renovate bot (for example https://github.com/nuxt-community/sentry-module/pull/309) so no need to create issues about that.

Since those dependencies are not pinned, you can force an update yourself using `yarn upgrade` or uninstalling and installing the module again.
