### ISSUE TITLE
Passing user information to Sentry

### ISSUE THREAD

**Issue by darrenchiu** [nuxt-community/sentry-module#386]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
To setUser context just like wt's described here:
https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/

What is the current best practice of setting user and pass it to sentry? To be particular, I am using nuxt-auth as well.

**Comment by rchl** [comment]
Personally for the server side I'm adding a server middleware so that it runs before all other middlewares. A middleware function like:

```js
(req, res, next) => {
    process.sentry.configureScope(scope => {
        scope.setUser({
            ip_address: req.ipAddress,

        });
    });
    next();
};
```

This sets user per-request. Of course you need to get the data like ip address and user id from request object or similar so you need other middlewares before that set it.

As for the client-side, I use a Nuxt plugin:

```js
/** @type {import('@nuxt/types').Plugin} */
export default ({ $sentry, store }) => {
    if ($authPlugin.isLoggedIn()) {
        $sentry.setUser({
            ip_address: store.state.ipAddress
            id: $authPlugin.id,
            username: $authPlugin.username,
        });
    }
};
```

I'm not sure if this could be generalized to be included in the module but I guess at least the documentation could document similar approach.

**Comment by darrenchiu** [comment]
@rchl works perfectly, closing it now. Thanks so much for your help.

**Comment by rchl** [comment]
I'd want to at least expand documentation. Any help welcome. :)
