### ISSUE TITLE
Sentry not working client side

### ISSUE THREAD

**Issue by robyedlin** [nuxt-community/sentry-module#4]
With a fresh nuxt starter package with google analytics module, sentry installed, and the DSN configured in the env, I can't get client side error reporting in Sentry to work.

To reproduce, I used the google analytics test setup with a bad UA. This raises an error and should report to Sentry, but doesn't seem to.

**Comment by DiederikvandenB** [comment]
I was not able to reproduce your issue when using a non-existing UA like `1234321`. I was however able to see a console (not Sentry) error when not providing a UA. The error I receive is:

`[nuxt] Error while initializing app Error: [vue-analytics] Please enter a Google Analytics tracking ID`

You can see that the `vue-analytics` package throws the error [here](https://github.com/MatteoGabriele/vue-analytics/blob/master/src/bootstrap.js#L19). Then, NuxtJS catches the error [here](https://github.com/nuxt/nuxt.js/blob/9e4f864e4d25af2e9668767bb297182656e19cba/lib/app/client.js#L62). As you can see, the error is caught and then logged to the console. Sentry will not capture console messages, and therefore you will not see the error logged to Sentry.

Since this is not a bug or an issue with the Sentry module package, I would advise to raise this issue with the Nuxt package. Hope this helps.

**Comment by robyedlin** [comment]
Ok!
