### ISSUE TITLE
Ignore external JS

### ISSUE THREAD

**Issue by EduardoMateos** [nuxt-community/sentry-module#444]
Hello guys!

I have a problem, any external JS from chrome extensions or any JS triggered by the user is registered in sentry. How can I ignore these errors? and report errors from my JS

<img width="718" alt="Captura de pantalla 2022-09-07 a las 12 12 57" src="https://user-images.githubusercontent.com/11529050/188853324-c3f6e198-463a-415e-9521-958b2c129437.png">

thanks guys

**Comment by rchl** [comment]
There are various settings in Sentry dashboard for ignoring certain types of errors like from extensions or other domains. You will still be charged for those by Sentry but they will be hidden. Otherwise you can add a [`beforeSend` hook ](https://docs.sentry.io/platforms/javascript/configuration/filtering/) in the config and apply any custom rules you want.

There is no 100% solution for ignoring all extension errors for example as there is no always a way to identify those properly.
