### ISSUE TITLE
Sentry: nuxtCtx.tryUse is not a function

### ISSUE THREAD

**Issue by febriardis** [nuxt-community/sentry-module#557]
### Version
@nuxtjs/sentry: 7.1.13
nuxt: nuxt bridge

when npm run dev i get error like this:

![image](https://user-images.githubusercontent.com/33593020/231969972-bab0d788-a01f-493b-819b-49bcf62ddd75.png)

**Comment by febriardis** [comment]
unctx is from sentry module. But now, i use sentry version 7.1.3, it's no such issue in my project

**Comment by rchl** [comment]
If you are not gonna answer my questions then I won't be able to help you. Using older version is not really a solution to the issue.

**Comment by febriardis** [comment]
@rchl this is bro 
![image](https://user-images.githubusercontent.com/33593020/232356241-72137b6e-415f-4b2c-b03e-abdf1d54b76b.png)

**Comment by rchl** [comment]
This is with latest module version?

**Comment by balesniy** [comment]
I have same problem
![image](https://user-images.githubusercontent.com/16609542/236209990-ca8b34da-461a-41b0-91b2-b07e663e9142.png)

**Comment by rchl** [comment]
I would expect there to be an error if 0.0.3 version of `unctx` is used but this module only imports `unctx` from the root of the module so I would expect it to resolve to the one within the `@nuxtjs/sentry`. Maybe Bridge changes something about where module's code is executed from... Any idea @danielroe ?

**Comment by danielroe** [comment]
No, Nuxt Bridge shouldn't change how the module code is executed or its dependencies are imported; `jiti` will be handling that, but it may well be an issue stemming from there (cc: @pi0).

I would recommend updating the critters module; the current version is much newer and depends on nuxt/kit v3.4.3.

**Comment by rchl** [comment]
Wouldn't upgrading to latest version of `@nuxtjs/critters` create additional type issues due to inclusion of `@nuxt/schema`? At least when running `yarn tsc` without `skipLibCheck`?

I've tried to reproduce it by installing `@nuxtjs/critters@0.2.0` module and also by forcing `unctx@0.0.3` to be hoisted but I couldn't reproduce.

Maybe the `jiti` dependency or some related one is outdated in your project and triggers some already fixed bug? You could run `npm upgrade` or `yarn upgrade` to update all dependencies including the implicit ones and see if that fixes it. Or alternatively delete the lock file and `node_modules` manually and re-install dependencies.
