### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'pt.push')

### ISSUE THREAD

**Issue by michalzaq12** [nuxt-community/sentry-module#611]
### Version
@nuxtjs/sentry: 7.4.0
nuxt: 2.16.3
Browser: Mobile Safari

Sentry config:
`lazy: true`

<img width="511" alt="image" src="https://github.com/nuxt-community/sentry-module/assets/28574933/c687e347-972d-4eb7-b94d-f2904054bcd9">

**Comment by rchl** [comment]
I'd need to see some more of your code that triggers this code. It seems like the code might be holding a reference to a specific mocked method and then using it after Sentry has loaded.

I could probably work around the crash but then an actual crash might just get silently ignored.

In any case, I would guess that it's probably not a new issue in your code base but you got it reported as new issue because of slightly different stack trace.

**Comment by rchl** [comment]
This should have been fixed by #606 and the fix was released in [v7.4.0](https://github.com/nuxt-community/sentry-module/releases/tag/v7.4.0)
